config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  get '/groups/:group_id/procedures/:procedure_id/stages/:id/next', 
      to: 'stages#next', 
      as: 'stage_next'
  get '/groups/:group_id/procedures/:procedure_id/stages/:id/previous', 
      to: 'stages#previous', 
      as: 'stage_previous'

  get '/groups/:group_id/procedures/:procedure_id/projects/:id/move_forward', 
      to: 'projects#move_forward', 
      as: 'project_stage_next'
  get '/groups/:group_id/procedures/:procedure_id/projects/:id/move_back', 
      to: 'projects#move_back', 
      as: 'project_stage_back'


  resources :groups do
    resources :procedures do
      resources :stages
      resources :projects
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Group < ApplicationRecord
	has_many :procedures, dependent: :destroy 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:title)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
  <div class = "group"> 
    <div class="group-header">
      <div>
        <h2> <strong> <%= group.title %> </strong> </h2> 
      </div>

      <div class="group-btn-group" role="group" style="display: flex;">
        <%= link_to "Edit", 
            edit_group_path(@group.id), 
            data: { turbo_method: "get" }, 
            class: 'btn btn-sm btn-primary'%> 

        <%= link_to "Add a procedure", 
            new_group_procedure_path(@group),
            class: 'btn btn-sm btn-success mx-1' %>
        
        <%= button_to "Destroy this group", 
            @group, 
            method: :delete, 
            class: 'btn btn-sm btn-danger' %>
      </div>

    </div> 
    <div class="procedures" data-controller="groups"> 
      <% group.procedures.each_with_index do |procedure, index| %> 
        <%= render procedure, index: index %>
      <%end%>        
    </div>
  </div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div data-controller="groups" class="groups-container">
  <p style="color: green"><%= notice %></p>

  <h1>Groups</h1>

  <div id="groups" class="groups-list">
    <% @groups.each do |group| %>
      <div class="group-card">
        <a href="/groups/<%= group.id %>" class="group-card_link">
          <div class="group-card_bg"></div>
          <div class="group-card_title">
            <h2> <strong> <%= group.title %> </strong> </h2> 
            <h4> <%= pluralize(group.procedures.count, "procedures") %> </h4> 
            <h4> <%= pluralize(group.procedures.map { |procedure| procedure.projects.count }.sum, "projects") %> </h4> 
          </div>      
        </a>
      </div>
    <% end %>
  </div>

  <%= link_to "New group", new_group_path, class: 'btn btn-sm btn-success' %>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Back to groups", groups_path, class: 'btn btn-danger' %>
<%= render @group %>