config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  get '/groups/:group_id/procedures/:procedure_id/stages/:id/next', 
      to: 'stages#next', 
      as: 'stage_next'
  get '/groups/:group_id/procedures/:procedure_id/stages/:id/previous', 
      to: 'stages#previous', 
      as: 'stage_previous'

  get '/groups/:group_id/procedures/:procedure_id/projects/:id/move_forward', 
      to: 'projects#move_forward', 
      as: 'project_stage_next'
  get '/groups/:group_id/procedures/:procedure_id/projects/:id/move_back', 
      to: 'projects#move_back', 
      as: 'project_stage_back'


  resources :groups do
    resources :procedures do
      resources :stages
      resources :projects
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/stage.rb
# == Schema Information
#
# Table name: stages
#
#  id           :integer          not null, primary key
#  stage_number :integer
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  procedure_id :integer          not null
#
# Indexes
#
#  index_stages_on_procedure_id  (procedure_id)
#
# Foreign Keys
#
#  procedure_id  (procedure_id => procedures.id)
#
class Stage < ApplicationRecord
  belongs_to :procedure
  has_many :projects
  
  validates :procedure_id, uniqueness: { scope: :stage_number,
    message: "this order number isn't available" }

  def next
    if procedure.stages.maximum("stage_number") == stage_number
      return 'already the last'
    else
      return procedure.stages.where("stage_number > ?", stage_number).first
    end
  end

  def previous
    if procedure.stages.minimum("stage_number") == stage_number
      return 'already the first'
    else
      return procedure.stages.where("stage_number < ?", stage_number).last
    end
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: %i[ show edit update destroy next previous]
  before_action :set_group, :set_procedure

  # GET /stages or /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1 or /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = @procedure.stages.build
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages or /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to group_procedure_path(@group, @procedure), notice: "Stage was successfully created." }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1 or /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to group_procedure_path(@group, @procedure), notice: "Stage was successfully updated." }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1 or /stages/1.json
  def destroy
    @stage.destroy

    respond_to do |format|
      format.html { redirect_to group_procedure_path(@group, @procedure), notice: "Stage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def next
    if @stage.next == 'already the last'
      redirect_to group_procedure_path(@group, @procedure) 
      return
    end
    next_stage = @stage.next
    cur_stage_number = @stage.stage_number
    next_stage_number = next_stage.stage_number

    @stage.stage_number = nil
    @stage.save
    next_stage.stage_number = cur_stage_number

    @procedure.stages.each do |stage|
      p stage
    end

    next_stage.save!
    
    @stage.stage_number = next_stage_number
    @stage.save!
    redirect_to group_procedure_path(@group, @procedure)
  end

  def previous
    if @stage.previous == 'already the first'
      redirect_to group_procedure_path(@group, @procedure) 
      return
    end
    previous_stage = @stage.previous
    cur_stage_number = @stage.stage_number
    previous_stage_number = previous_stage.stage_number

    @stage.stage_number = nil
    @stage.save
    previous_stage.stage_number = cur_stage_number

    previous_stage.save!
    
    @stage.stage_number = previous_stage_number
    @stage.save!
    redirect_to group_procedure_path(@group, @procedure)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    def set_procedure
      @procedure = Procedure.find(params[:procedure_id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end    

    # Only allow a list of trusted parameters through.
    def stage_params
      params.require(:stage).permit(:title, :procedure_id)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_with model: [@group, @procedure, stage] do |form| %>
  <% if stage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
        <% stage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div style = "display: none" >
    <%= form.label :procedure_id %>
    <%= form.text_field :procedure_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stages/_stage.html.erb
<div class="cardy" style="display: none;">
  <div class="face face1">
    <div class="stage-card_header">
      <%= link_to '<', 
        stage_previous_path(
          stage.procedure.group.id,
          stage.procedure.id,
          stage), 
        class: 'btn btn-sm btn-primary' %>
      <h4>
        <strong><%= stage.title %></strong>
      </h4>
      <%= button_to '>', 
          stage_next_path(
            stage.procedure.group.id,
            stage.procedure.id,
            stage), 
          class: 'btn btn-sm btn-primary btn-stage' %> 
    </div>
    <div class="stage-card_footer">  
      <%= link_to 'Edit', 
          edit_group_procedure_stage_path(
            stage.procedure.group.id,
            stage.procedure.id,
            stage), 
          data: { turbo_method: "get" }, 
          class: 'btn btn-sm btn-primary'%>
      <%= link_to "Destroy",
          group_procedure_stage_path(
            stage.procedure.group.id,
            stage.procedure.id,
            stage.id), 
          data:{
            turbo_method: "delete",
            turbo_confirm: "Are you sure?"}, 
          class: 'btn btn-sm btn-danger' %>
    </div>
  </div>
  <div class="face face2">
    <div class="projects">
      <% stage.projects.each do |project| %>
        <%= render project %>
      <% end %>
    </div>

  </div>
</div>


<div class="stage-card">
  <div class="stage-card-header">
    <div class="row align-items-center justify-content-md-center">
      <div class="col-2">
        <%= link_to '<', 
          stage_previous_path(
            stage.procedure.group.id,
            stage.procedure.id,
            stage), 
          class: 'btn btn-sm btn-primary' %>
      </div>
      <div class="col-md-auto justify-content-center">
        <h4>
          <strong><%= stage.title %></strong>
        </h4>
      </div>
      <div class="col-2">
        <%= button_to '>', 
            stage_next_path(
              stage.procedure.group.id,
              stage.procedure.id,
              stage), 
            class: 'btn btn-sm btn-primary btn-stage' %> 
      </div>
    </div>
    <div class="row align-items-center justify-content-md-center">  
      <%= link_to 'Edit', 
          edit_group_procedure_stage_path(
            stage.procedure.group.id,
            stage.procedure.id,
            stage), 
          data: { turbo_method: "get" }, 
          class: 'btn btn-sm btn-primary col-4'%>
      <%= link_to "Destroy",
          group_procedure_stage_path(
            stage.procedure.group.id,
            stage.procedure.id,
            stage.id), 
          data:{
            turbo_method: "delete",
            turbo_confirm: "Are you sure?"}, 
          class: 'btn btn-sm btn-danger col-4' %>
    </div>
  </div>
  <div class="stage-card-body">
    <div class="projects">
      <% stage.projects.each do |project| %>
        <div class="stage-project row align-items-center justify-content-md-center mb-1" 
       id="project-<%= project.id%>-<%=project.procedure.id%>">
          <%= render project %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stages/edit.html.erb
<h1>Editing stage</h1>

<%= render "form", stage: @stage %>

<br>

<div>
  <%= link_to "Back to procedures", group_procedures_path(@group) %>
</div>

app/views/stages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stages</h1>

<div id="stages">
  <% @stages.each do |stage| %>
    <%= render stage %>
    <p>
      <%= link_to "Show this stage", stage %>
    </p>
  <% end %>
</div>

<%= link_to "New stage", new_stage_path %>

app/views/stages/new.html.erb
<h1>New stage</h1>

<%= render "form", stage: @stage %>

<br>

<div>
  <%= link_to "Back to procedure", group_procedure_path(@group, @procedure) %>
</div>

app/views/stages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stage %>

<div>
  <%= link_to "Edit this stage", edit_stage_path(@stage) %> |
  <%= link_to "Back to stages", stages_path %>

  <%= button_to "Destroy this stage", @stage, method: :delete %>
</div>