config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  get '/groups/:group_id/procedures/:procedure_id/stages/:id/next', 
      to: 'stages#next', 
      as: 'stage_next'
  get '/groups/:group_id/procedures/:procedure_id/stages/:id/previous', 
      to: 'stages#previous', 
      as: 'stage_previous'

  get '/groups/:group_id/procedures/:procedure_id/projects/:id/move_forward', 
      to: 'projects#move_forward', 
      as: 'project_stage_next'
  get '/groups/:group_id/procedures/:procedure_id/projects/:id/move_back', 
      to: 'projects#move_back', 
      as: 'project_stage_back'


  resources :groups do
    resources :procedures do
      resources :stages
      resources :projects
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/procedure.rb
# == Schema Information
#
# Table name: procedures
#
#  id         :integer          not null, primary key
#  title      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer          not null
#
# Indexes
#
#  index_procedures_on_group_id  (group_id)
#
# Foreign Keys
#
#  group_id  (group_id => groups.id)
#
class Procedure < ApplicationRecord
	belongs_to :group
	has_many   :stages
	has_many   :projects
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: %i[ show edit update destroy ]
  before_action :set_group

  def index
    @procedures = @group.procedures.all
  end

  def show
    @stages = @procedure.stages.order(stage_number: :asc)
  end

  def new
    @procedure = @group.procedures.new
  end

  def edit
  end

  def create

    @procedure = @group.procedures.new(procedure_params)

    respond_to do |format|
      if @procedure.save
        format.html { redirect_to @group, notice: "Procedure was successfully created." }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to group_procedure_url(@group, @procedure), notice: "Procedure was successfully updated." }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @procedure.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Procedure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def procedure_params
      params.require(:procedure).permit(:title)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_with model: [@group, @group.procedures.build] do |form| %>
  <% if procedure.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(procedure.errors.count, "error") %> prohibited this procedure from being saved:
      </h2>

      <ul>
        <% procedure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/procedures/_procedure.html.erb
	<div class="procedure-card" 
	     id=<%= procedure.group.id%>-<%=procedure.id%> 
	     data-action="click->groups#getProcedure"
	     data-groups-target="procedure"> 
	  <h4 class="group-title">
	  	<strong id=<%= procedure.group.id%>-<%=procedure.id%>>
	    	<%= procedure.title%>
	  	</strong>
	  </h4>
	  <div>
	    <%= link_to 'Edit', 
	    		edit_group_procedure_path(procedure.group.id, procedure.id), 
	    		data: { turbo_method: "get" }, 
	    		class: 'btn btn-sm btn-primary'%>

	    <%= link_to 'Open', 
	    		group_procedure_path(procedure.group.id, procedure.id), 
	    		data: { turbo_method: "get" }, 
	    		class: 'btn btn-sm btn-success'%>	    	

	    <%= link_to 'Destroy', 
	    		group_procedure_path(procedure.group.id,procedure.id), 
	    		data: { turbo_method: "delete",
	    				action: "click->groups#destroyProcedure" }, 
	    		class: 'btn btn-sm btn-danger' %>
	  </div>
	  <div class="procedure-stages">

	  </div>	
	</div> 

app/views/procedures/edit.html.erb
<%= turbo_frame_tag @procedure do %>
  <div class="group-card" >
    <h1>Editing procedure</h1>

    <%= render "form", procedure: @procedure %>

    <br>

    <div>
      <%= link_to "Back to procedures", group_procedures_path(@group) %>
    </div>

  </div>
<% end %>

app/views/procedures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Procedures</h1>

<div id="procedures">
  <% @procedures.each do |procedure| %>
    <%= render procedure %>
    <p>
      <%= link_to "Show this procedure", group_procedure_path(@group, procedure) %>
    </p>
  <% end %>
</div>

<%= link_to "New procedure", new_group_procedure_path(@group) %>

app/views/procedures/new.html.erb
<h1>New procedure</h1>

<%= render "form", procedure: @procedure %>

<br>

<div>
  <%= link_to "Back to procedures", group_procedures_path(@group) %>
</div>

app/views/procedures/show.html.erb
<p style="color: green"><%= notice %></p>

<h4 class="group-title">
  <strong id=<%= @procedure.group.id%>-<%=@procedure.id%>>
    <%= @procedure.title%>
  </strong>
</h4>

<div>
  <%= link_to 'Edit', 
      edit_group_procedure_path(@procedure.group.id, @procedure.id), 
      data: { turbo_method: "get" }, 
      class: 'btn btn-sm btn-primary'%>

  <%= link_to 'Create a project', 
      new_group_procedure_project_path(@procedure.group.id, @procedure.id), 
      data: { turbo_method: "get" }, 
      class: 'btn btn-sm btn-success'%>       

  <%= link_to 'Destroy', 
      group_procedure_path(@procedure.group.id,@procedure.id), 
      data: { turbo_method: "delete",
          action: "click->groups#destroyProcedure" }, 
      class: 'btn btn-sm btn-danger' %>
</div>

<div class="stages">
  <% @stages.each do |stage| %>
    <%= render stage %>
  <% end %>
</div>

  <%= link_to 'Add a stage', 
      new_group_procedure_stage_path(@procedure.group.id, @procedure.id), 
      data: { turbo_method: "get"}, 
      class: 'btn btn-sm btn-success' %>